--CREATE DATABASE SENAI_HROADS_MANHA

--USE SENAI_HROADS_MANHA

CREATE TABLE TIPO_HABILIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE CLASSES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE HABILIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL
	,ID_TIPO_HABILIDADES INT FOREIGN KEY REFERENCES TIPO_HABILIDADES(ID) 
);

CREATE TABLE CLASSES_HABILIDADES(
	ID_CLASSES INT FOREIGN KEY REFERENCES CLASSES(ID) NOT NULL
	,ID_HABILIDADES INT FOREIGN KEY REFERENCES HABILIDADES(ID)
);

CREATE TABLE PERSONAGEN(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL	
	,CP_DE_VIDA_MAXIMA INT NOT NULL
	,CP_DE_MANA_MAXIMA INT NOT NULL
	,ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID)
	,DATA_CRIACAO DATETIME NOT NULL
	,DATA_ATUALIZACAO DATETIME NOT NULL
);

