CREATE DATABASE SENAI_SSOLVE_MANHA;

CREATE TABLE FUNCIONARIOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL
);

CREATE TABLE ITEM_AREA(
	ID INT IDENTITY PRIMARY KEY
	,ITEM VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE TIPO_SERVICO(
	ID INT IDENTITY PRIMARY KEY
	,TIPO VARCHAR(250) UNIQUE NOT NULL
);


CREATE TABLE AREA(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL 
);

CREATE TABLE CLIENTE(
	ID INT IDENTITY PRIMARY KEY
	,NOME_FANTASIA VARCHAR(250) UNIQUE NOT NULL
	,CNPJ CHAR(14) UNIQUE NOT NULL
	,RAZAO_SOCIAL VARCHAR(250) NOT NULL
	,ENDERECO VARCHAR(250) NOT NULL
);

CREATE TABLE SERVICO(
	ID INT IDENTITY PRIMARY KEY
	,DESCRICAO TEXT NOT NULL
	,HORARIO_INICIO DATETIME NOT NULL
	,HORARIO_FIM DATETIME NOT NULL
	,ID_TIPO_SERVICO INT FOREIGN KEY REFERENCES TIPO_SERVICO(ID)
	,ID_ITEM_AREA INT FOREIGN KEY REFERENCES ITEM_AREA(ID)
	,ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID)
	,ID_AREA INT FOREIGN KEY REFERENCES AREA(ID)
	,PRECO DECIMAL NOT NULL
);


CREATE TABLE SERVICO_FUNCIONARIO(
	ID_SERVICO INT FOREIGN KEY REFERENCES SERVICO(ID)
	,ID_FUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIOS(ID)
);

--ALTER TABLE SERVICO_FUNCIONARIO
--DROP COLUMN PRECO

--ALTER TABLE SERVICO
--ADD PRECO DECIMAL NOT NULL

DROP DATABASE SENAI_SSOLVE_MANHA